import { test, expect, type Page } from "@playwright/test";
import { installHttpFixture } from "./support/http-fixture";
const base = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
async function login(page:Page,id="GV0001") {await page.goto(base+"/login/");await page.getByLabel("ID giảng viên").fill(id);await page.getByLabel("Mật khẩu",{exact:true}).fill("Demo123!");await page.getByRole("button",{name:"Đăng nhập",exact:true}).click();await expect(page).toHaveURL(/\/home\//);}
test.beforeEach(async({page})=>{if(process.env.NEXT_PUBLIC_USE_MOCK!=="true") await installHttpFixture(page);});
test("Giảng viên xem báo cáo, sửa nhận xét, guide không chặn và controls ẩn/hiện biểu đồ",async({page})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await login(page);
 await page.goto(base+"/class/?classId=class-green");await page.getByRole("tab",{name:"Hồ sơ & quan hệ",exact:true}).click();await page.getByRole("link",{name:"Báo cáo học tập",exact:true}).first().click();await expect(page.getByRole("heading",{name:"Tổng quan kết quả Unit 3"})).toBeVisible();await expect(page.getByRole("button",{name:"Sửa nhận xét",exact:true})).toBeEnabled();
 await page.getByRole("button",{name:"Hướng dẫn",exact:true}).click();const guide=page.getByRole("complementary",{name:"Hướng dẫn màn hình hiện tại"});await expect(guide).toBeVisible();await expect(guide.getByRole("heading",{name:"Báo cáo học tập",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Thu nhỏ giao diện",exact:true}).click();await expect(page.getByTestId("application-scale")).toHaveAttribute("data-zoom","85");
 await page.screenshot({path:"test-results/staff-report-guide-desktop.png",fullPage:true});await page.getByRole("button",{name:"Sửa nhận xét",exact:true}).click();const dialog=page.getByRole("dialog");await dialog.getByLabel("Nhận xét Vocabulary",{exact:true}).fill("Nhận xét đã cập nhật\nQua báo cáo");await dialog.getByLabel("Nhận xét tổng thể",{exact:true}).fill("Báo cáo mới");await dialog.getByRole("button",{name:"Lưu nhận xét",exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByText("Đã cập nhật nhận xét trên báo cáo học sinh.",{exact:true})).toBeVisible();await expect(page.getByText("Báo cáo mới",{exact:true})).toBeVisible();
 await page.getByTestId("skills-chart").scrollIntoViewIfNeeded();await page.getByRole("button",{name:"Ẩn Vocabulary",exact:true}).click();await expect(page.getByRole("button",{name:"Hiện Vocabulary",exact:true})).toHaveAttribute("aria-pressed","false");await page.getByRole("button",{name:"Hiện Vocabulary",exact:true}).click();await expect(page.getByRole("button",{name:"Ẩn Vocabulary",exact:true})).toHaveAttribute("aria-pressed","true");
 await page.getByRole("heading",{name:"Thay đổi điểm theo từng kỹ năng qua các Unit"}).scrollIntoViewIfNeeded();await expect(page.getByTestId("change-chart")).toHaveCount(8);await page.getByRole("button",{name:"Ẩn tất cả biểu đồ thay đổi",exact:true}).click();await expect(page.getByTestId("change-chart")).toHaveCount(0);await page.getByRole("button",{name:"Hiện tất cả biểu đồ thay đổi",exact:true}).click();await expect(page.getByTestId("change-chart")).toHaveCount(8);
 await guide.getByRole("button",{name:"Ẩn hướng dẫn",exact:true}).click();await expect(guide).not.toBeVisible();await page.reload();await expect(page.getByTestId("application-scale")).toHaveAttribute("data-zoom","85");await expect(page.getByText("Báo cáo mới",{exact:true})).toBeVisible();expect(errors).toEqual([]);
});
test("Manager chỉ xem, mobile tối guide vẫn cho đổi Unit và zoom",async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({colorScheme:"dark"});await login(page,"MG0001");await page.goto(base+"/reports/?classId=class-green&studentId=HV1001");await expect(page.getByRole("button",{name:"Sửa nhận xét",exact:true})).toBeDisabled();await expect(page.getByRole("heading",{name:"Tổng quan kết quả Unit 3"})).toBeVisible();
 await page.getByRole("button",{name:"Hướng dẫn",exact:true}).click();const guide=page.getByRole("complementary",{name:"Hướng dẫn màn hình hiện tại"});await expect(guide).toBeVisible();await page.getByRole("button",{name:"Thu nhỏ giao diện",exact:true}).click();await page.getByRole("combobox",{name:"Học sinh",exact:true}).click();await page.getByRole("option",{name:/Minh Anh/}).click();await expect(page.getByText("Học sinh chưa có Unit hoặc báo cáo đã công bố trong lớp này.",{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:"test-results/staff-report-guide-mobile-dark.png",fullPage:true});await guide.getByRole("button",{name:"Ẩn hướng dẫn",exact:true}).click();await expect(guide).not.toBeVisible();
});
